version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"


  
volumes:
  mysql_data:
